[project]
name = "food-diary-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.15.2",
    "pydantic-settings>=2.8.1",
    "python-fasthtml>=0.12.6",
    "resend>=2.7.0",
    "sqlalchemy>=2.0.40",
    "uuid6>=2024.7.10",
]

[tool.setuptools]
packages = ["app"]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
