"""empty message

Revision ID: fccbe1d126a6
Revises: 
Create Date: 2025-04-13 22:32:44.808539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.user import UuidAsBinary


# revision identifiers, used by Alembic.
revision: str = 'fccbe1d126a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UuidAsBinary(length=16), nullable=False),
    sa.Column('public_id', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('email_verification_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('NOT(is_anonymous = false AND email IS NULL)', name='ck_user_registered_email'),
    sa.CheckConstraint('NOT(is_anonymous = false AND password_hash IS NULL)', name='ck_user_registered_password'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_anon_cleanup', 'users', ['is_anonymous', 'last_active_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verification_token'), 'users', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_users_is_anonymous'), 'users', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_anonymous'), table_name='users')
    op.drop_index(op.f('ix_users_email_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_anon_cleanup', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
